from llm_sdk.tool_functions import (
    CONVERT_CURRENCY_TOOL,
    CURRENT_TIME_TOOL,
    WEB_SEARCH_TOOL,
    WEATHER_TOOL,
)

DEFAULT_CHAT_TOOLS = [
    CURRENT_TIME_TOOL,
    WEATHER_TOOL,
    CONVERT_CURRENCY_TOOL,
    WEB_SEARCH_TOOL,
]
